#!/bin/bash  
  
stages=("Dev" "QA" "Prod")  
dependentMap=("" "Dev-placeholder" "QA-placeholder,Dev-placeholder")  
  
stackTemplate='  
    {{.StackName}}-site:  
        uses: ./.github/workflows/site-cd-workflow.yml  
        with:  
            working-directory: {{.Stage}}/{{.StackName}}  
        secrets: inherit  
        needs: [{{.DependentStageList}}]  
'  
  
stageTemplate='  
    {{.Stage}}-placeholder:  
        name: {{.Stage}}  
        needs: [{{.StackList}}]  
        runs-on: ubuntu-latest  
        steps:  
         - run: echo "running {{.Stage}} stage"  
'  
  
workflow='  
name: Terraform apply infra change  
  
on:  
  push:  
    branches: ["main"]  
  
jobs:  
'  
backendTemplate='
terraform {
  backend "azurerm" {
    resource_group_name  = "terraformbackend"
    storage_account_name = "demobackend"
    container_name       = "tfbackend"
    key                  = "{{.StackName}}.tfstate"
  }
}
'
  
for count in "${!stages[@]}"; do  
    stage=${stages[$count]}  
    IFS=$'\n' read -ra iacgroups <<< "$(find "./$stage" -maxdepth 1 -mindepth 1 -type d -printf '%f\n')"  
    if [ ${#iacgroups[@]} -eq 0 ]; then  
        continue  
    fi  
    stacklist=()  
    for iacgroup in "${iacgroups[@]}"; do  
        stacklist+=("$iacgroup-site")  
    done  
    stagejob=$(echo "$stageTemplate" | sed "s/{{.Stage}}/$stage/g" | sed "s/{{.StackList}}/$(IFS=,; echo "${stacklist[*]}")/g")  
    workflow+="$stagejob"  
    dependentStageList=${dependentMap[$count]}  
    for iacgroup in "${iacgroups[@]}"; do  
        stackjob=$(echo "$stackTemplate" | sed "s/{{.StackName}}/$iacgroup/g" | sed "s/{{.Stage}}/$stage/g" | sed "s/{{.DependentStageList}}/$dependentStageList/g")  
        #generate backend config file for each stack
        backendConfigFile="./$stage/$iacgroup/backend.tf"
        if [ -f "$backendConfigFile" ]; then  
            rm "$backendConfigFile"  
        fi
        echo "$backendTemplate" | sed "s/{{.StackName}}/$iacgroup/g" > "$backendConfigFile"
        git add $backendConfigFile
        workflow+="$stackjob"  
    done  
done  
  
# create a workflow file  
workflowfile="./.github/workflows/deploy-infra.yml"  
if [ -f "$workflowfile" ]; then  
    rm "$workflowfile"  
fi  
echo "$workflow" > "$workflowfile"  
git add $workflowfile
