#!/bin/bash
set -e
  
stages=("Dev" "QA" "Prod")
  
groupTemplate='
    {{.GroupName}}:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: {{.Stage}}/{{.GroupName}}
        secrets: inherit
        needs: [{{.Stage}}]
'

stageTemplate='
    {{.Stage}}:
        name: {{.Stage}}
        needs: [{{.GroupList}}]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running {{.Stage}} stage"
'

workflow='
name: Terraform apply infra change

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
'
backendTemplate=$(<.azure/backendTemplate.tf)
  
for count in "${!stages[@]}"; do
    stage=${stages[$count]}

    if [ $count -eq 0 ]; then
        stagejob=$(echo "$stageTemplate" | sed "s/{{.Stage}}/$stage/g" | grep -v 'needs: \[.*\]')
        workflow+="$stagejob"
    else
        groupList=()
        pushd ./${stages[$count-1]}
        groupList+=${stages[$count-1]}
        for d in */ ; do
            if [ $d = "*/" ]; then
                break
            fi
            groupList+=$(echo "$d" | sed 's/\///g' | sed 's/ /_/g')
        done
        stagejob=$(echo "$stageTemplate" | sed "s/{{.Stage}}/$stage/g" | sed "s/{{.GroupList}}/$(IFS=,; echo "${groupList[*]}")/g")
        workflow+="$stagejob"
        popd
    fi

    pushd ./$stage
    for d in */ ; do
        if [ $d = "*/" ]; then
            break
        fi
        group=$(echo "$d" | sed 's/\///g' | sed 's/ /_/g')
        groupjob=$(echo "$groupTemplate" | sed "s/{{.GroupName}}/$group/g" | sed "s/{{.Stage}}/$stage/g")
        workflow+="$groupjob"
    done
    popd
done

# create a workflow file
workflowfile="./.github/workflows/deploy-infra.yml"
if [ -f "$workflowfile" ]; then
    rm "$workflowfile"
fi  
echo "$workflow" > "$workflowfile"
git add $workflowfile
