name: Terraform apply infra change

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    provide_paths:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Set matrix 
              id: set-matrix
              run: |
                echo "sites=['dev, dev/sample, dev/test','qa, qa/test2','prod']">>$GITHUB_OUTPUT
        outputs:
            sites: ${{ steps.set-matrix.outputs.sites }}
    terraform_apply_for_stages:
        runs-on: ubuntu-latest
        needs: provide_paths
        strategy:
            matrix:
              sites: ${{ fromJson(needs.provide_paths.outputs.sites) }}
            max-parallel: 1
        steps:
            - uses: ./.github/workflows/terraform-apply.yml
              with:
                  sites: ${{ matrix.sites }}
          
