name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    dev:
        name: dev
        runs-on: ubuntu-latest
        steps:
         - run: echo "running dev stage"
    Arizona:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/Arizona
        secrets: inherit
        needs: [dev]
    Media:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/Media
        secrets: inherit
        needs: [dev]
    sample:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/sample
        secrets: inherit
        needs: [dev]
    qa:
        name: qa
        needs: [dev,Arizona,Media,sample]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running qa stage"
    prod:
        name: prod
        needs: [qa]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running prod stage"
