  
name: Terraform apply infra change  
  
on:  
  push:  
    branches: ["main"]  
  
jobs:  
  
    Dev-placeholder:  
        name: Dev  
        needs: [sample-site]  
        runs-on: ubuntu-latest  
        steps:  
         - run: echo "running Dev stage"    
    sample-site:  
        uses: ./.github/workflows/site-cd-workflow.yml  
        with:  
            working-directory: Dev/sample  
        secrets: inherit  
        needs: []  
