name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    needs: [init]
    uses: ./.github/workflows/list-and-run.yml
    secrets: inherit
    with:
      directory: dev
      
  qa:
    needs: [dev]
    uses: ./.github/workflows/list-and-run.yml
    secrets: inherit
    with:
      directory: qa
    
  prod:
    needs: [dev]
    uses: ./.github/workflows/list-and-run.yml
    secrets: inherit
    with:
      directory: prod