name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    dev:
        name: dev
        runs-on: ubuntu-latest
        steps:
         - run: echo "running dev stage"
    Media:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/Media
        secrets: inherit
        needs: [dev]
    sample:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/sample
        secrets: inherit
        needs: [dev]
    Toronto:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/Toronto
        secrets: inherit
        needs: [dev]
    qa:
        name: qa
        needs: [dev,Media,sample,Toronto]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running qa stage"
    Colorado:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: qa/Colorado
        secrets: inherit
        needs: [qa]
    prod:
        name: prod
        needs: [qa,Colorado]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running prod stage"
