
name: Terraform apply infra change

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:

    dev:
        name: dev
        runs-on: ubuntu-latest
        steps:
         - run: echo "running dev stage"
    sample:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/sample
        secrets: inherit
        needs: [dev]
    test:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/test
        secrets: inherit
        needs: [dev]
    qa:
        name: qa
        needs: [dev,sample,test]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running qa stage"
    1611:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: qa/1611
        secrets: inherit
        needs: [qa]
    prod:
        name: prod
        needs: [qa,1611]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running prod stage"
