name: Site Deployment

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true
  TF_VAR_subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_localAdminUser: ${{ secrets.localAdminUser }}
  TF_VAR_localAdminPassword: ${{ secrets.localAdminPassword }}
  TF_VAR_domainAdminUser: ${{ secrets.domainAdminUser }}
  TF_VAR_domainAdminPassword: ${{ secrets.domainAdminPassword }}
  TF_VAR_deploymentUserPassword: ${{ secrets.deploymentUserPassword }}
  TF_VAR_servicePrincipalId: ${{ secrets.servicePrincipalId }}
  TF_VAR_servicePrincipalSecret: ${{ secrets.servicePrincipalSecret }}
  TF_VAR_rpServicePrincipalObjectId: ${{ secrets.rpServicePrincipalObjectId }}
  TF_VAR_runnumber: ${{ github.run_number }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
        - run: echo "${{ inputs.working-directory }}"